# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2917036bff09468404e6d313e893641e1ee6f3013240663e6b27f0a9e53717fbb98a58ec381abee1f340334dbe7927fb7fe3a7ef9eef4b6eb945f5714fc20a01

test:
  secret_key_base: 6df8824e3801ed21bf04a558f68b764cf5fa0a9599d021a4d3df8ce08c2aa7426c3bcb8523c6d2b8c0646c8f1f9098cc0818dee4ed6386f0811ca0cd2abe8866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
